version: '3.1'
services:
  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: whiteboard
      POSTGRES_USER: whiteboard

  t-online-whiteboard:
    image: tanacsg/t-online-whiteboard:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      QUARKUS_DATASOURCE_PASSWORD: whiteboard
      QUARKUS_DATASOURCE_USER: whiteboard
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://postgresdb:5432/whiteboard
