# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Build with Maven
      run: mvn package -Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true      
    - name: Build Docker image
      run: docker build . --file Dockerfile --tag tanacsg/t-online-whiteboard:0.1.$GITHUB_RUN_NUMBER --tag tanacsg/t-online-whiteboard:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
          username: tanacsg
          password: ${{ secrets.TANACSG_TOKEN }}
    - name: Push Docker image
      run: docker push tanacsg/t-online-whiteboard --all-tags  
